$(function(){
	$("#btn-tableEdit").click(function(){
		$("#btn-notableEdit").show(500);
		$("#gro-tableName").show(500);
	});
	$("#btn-notableEdit").click(function(){
		$("#btn-notableEdit").hide(500);
		$("#gro-tableName").hide(500);
	});
});
$(function(){
	$("#btn-tableNumEdit").click(function(){
		$("#btn-notableNumEdit").show(500);
		$("#gro-tableNum").show(500);
	});
	$("#btn-notableNumEdit").click(function(){
		$("#btn-notableNumEdit").hide(500);
		$("#gro-tableNum").hide(500);
	});
});
